#!/bin/sh

version=$(git describe --abbrev=0 --tags)
name="dsv-$version-x86_64-unknown-linux-gnu"

mkdir -p ./builds/
cargo build --release
rm -rf "/tmp/$name"
mkdir "/tmp/$name"
cp ./target/release/dsv "/tmp/$name/"
cp ./README.md "/tmp/$name/"
cp ./UNLICENSE "/tmp/$name/"
tar zcf "./builds/$name.tar.gz" -C /tmp $name

